# SCG-YOLOv9n: YOLOv9n backbone + C‑SPD (early downsample), S‑CARAFE (neck up), GhostShuffle head
# This is a high-level topology; Ultralytics will map (from,to,module,args) tuples.


# depth,multipliers can be adjusted if you want a slightly bigger/smaller model
nc: 1 # overwrite at runtime based on dataset


backbone:
# from, number, module, args
[
[-1, 1, Conv, [64, 3, 2]], # P1/2
[-1, 1, CSPD, [64]], # C‑SPD replaces early strided downsample
[-1, 2, Conv, [128, 3, 2]], # P2/4
[-1, 1, C2f, [128, True]],
[-1, 1, Conv, [256, 3, 2]], # P3/8
[-1, 3, C2f, [256, True]],
[-1, 1, Conv, [512, 3, 2]], # P4/16
[-1, 3, C2f, [512, True]],
[-1, 1, Conv, [1024, 3, 2]], # P5/32
[-1, 1, SPPF, [1024, 5]],
]


neck:
[
[-1, 1, SCARAFE, [512]], # upsample 32→16
[[-1, 7], 1, Concat, [1]],
[-1, 3, C2f, [512]],


[-1, 1, SCARAFE, [256]], # upsample 16→8
[[-1, 5], 1, Concat, [1]],
[-1, 3, C2f, [256]],


[-1, 1, Conv, [256, 3, 2]], # down 8→16
[[-1, 10], 1, Concat, [1]],
[-1, 3, C2f, [512]],


[-1, 1, Conv, [512, 3, 2]], # down 16→32
[[-1, 9], 1, Concat, [1]],
[-1, 3, C2f, [1024]],
]


head:
[
[[12, 15, 18], 1, GhostShuffle, [nc]] # detection head (3 scales)
]